# Generated by Django 3.2.5 on 2021-07-15 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_funcionario_produto_salariomensal_servicos_tarefasagendadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefasagendadas',
            name='horario_fim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='horario_fim_da_tarefa', to='core.horario'),
        ),
        migrations.AddField(
            model_name='tarefasagendadas',
            name='horario_inicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='horario_inicio_da_tarefa', to='core.horario'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.DateTimeField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='duracao',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
