# Generated by Django 3.2.5 on 2021-07-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210715_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='dt_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='duracao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tarefasagendadas',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarefasagendadas',
            name='horario_fim',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tarefasagendadas',
            name='horario_inicio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
