# Generated by Django 3.2.5 on 2021-07-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210715_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='situacao',
            field=models.CharField(default='TRABALHANDO', max_length=100, null=True),
        ),
    ]
