# Generated by Django 3.2.5 on 2021-07-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_funcionario_situacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salariomensal',
            name='comissao_total',
        ),
        migrations.AddField(
            model_name='salariomensal',
            name='data_pagamento',
            field=models.DateField(null=True),
        ),
    ]
