# Generated by Django 3.2.5 on 2021-08-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210804_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
